# Generated by Django 3.1.7 on 2021-03-19 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30, verbose_name='Book title')),
                ('pic', models.ImageField(upload_to='uploads/', verbose_name='Picture')),
                ('book_description', models.TextField(blank=True, null=True, verbose_name='Book description')),
                ('author', models.CharField(max_length=30, verbose_name='Author name')),
                ('genre_type', models.CharField(max_length=30, verbose_name='Genre')),
                ('age', models.CharField(blank=True, max_length=30, null=True, verbose_name='Age category')),
                ('publishing', models.CharField(blank=True, max_length=30, null=True, verbose_name='Publishing')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rating value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing', models.TextField(blank=True, null=True, verbose_name='Publishing')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishings', to='references.book', verbose_name='Book')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type', models.CharField(max_length=30, verbose_name='Genre')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='references.book', verbose_name='Book')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30, verbose_name='Author name')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='references.book', verbose_name='Book')),
            ],
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.TextField(blank=True, null=True, verbose_name='Age category')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ages', to='references.book', verbose_name='Book')),
            ],
        ),
    ]
