# Generated by Django 3.1.5 on 2021-02-05 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(max_length=50, verbose_name='Genre name')),
                ('Reviews', models.TextField(blank=True, max_length=200, null=True, verbose_name='Reviews')),
                ('Rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rating value')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Values', to='references.author', verbose_name='Author')),
            ],
        ),
    ]
