# Generated by Django 3.1.5 on 2021-02-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20210205_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date time'),
        ),
    ]
