# Generated by Django 3.1.5 on 2021-02-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_auto_20210205_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(max_length=50, verbose_name='Genre name')),
                ('Reviews', models.TextField(blank=True, max_length=200, null=True, verbose_name='Reviews')),
                ('Rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rating value')),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Author_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Author_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.AddField(
            model_name='opinion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Opinions', to='references.author', verbose_name='Author'),
        ),
    ]
