# Generated by Django 3.1.7 on 2021-03-01 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_auto_20210212_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/', verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
