# Generated by Django 3.1.7 on 2021-03-22 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210322_0154'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('customer_cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cart.customercart', verbose_name='Basket')),
                ('phone', models.CharField(blank=True, default='', max_length=80, verbose_name='Phone')),
                ('country', models.CharField(blank=True, default='', max_length=80, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='', max_length=80, verbose_name='City')),
                ('post_index', models.CharField(blank=True, default='', max_length=80, verbose_name='Post-code')),
                ('address1', models.CharField(blank=True, default='', max_length=120, verbose_name='Address')),
                ('comments', models.TextField(blank=True, default='', max_length=1000, verbose_name='Comments')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date of changing')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatuses', verbose_name='Status'),
        ),
    ]
