# Generated by Django 3.1.7 on 2021-03-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20210321_1507'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.book', verbose_name='Book in cart')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='cart.cart', verbose_name='Cart')),
            ],
        ),
        migrations.DeleteModel(
            name='AuthorInCart',
        ),
    ]
